apiVersion: v1
kind: Namespace
metadata:
  name: tnr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: node-removal
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: node-removal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-removal
subjects:
- kind: ServiceAccount
  name: node-removal
  namespace: tnr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-removal
  namespace: tnr-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: terminated-node-removal
  namespace: tnr-system
spec:
  selector:
    matchLabels:
      name: terminated-node-removal
  template:
    metadata:
      labels:
        name: terminated-node-removal
    spec:
      serviceAccount: node-removal
      serviceAccountName: node-removal
      containers:
      - name: terminated-node-removal
        image: annavarsatish/node-removal:1.5
