apiVersion: v1
kind: Namespace
metadata:
  name: tnr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: node-removal
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: node-removal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-removal
subjects:
- kind: ServiceAccount
  name: node-removal
  namespace: tnr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-removal
  namespace: tnr-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: terminated-node-removal
  namespace: tnr-system
spec:
  schedule: "0/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          serviceAccount: node-removal
          serviceAccountName: node-removal
          restartPolicy: Never
          containers:
          - name: terminated-node-removal
            image: annavarsatish/node-removal:1.7-while
