apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: terminated-node-removal
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: terminated-node-removal
  template:
    metadata:
      labels:
        name: terminated-node-removal
    spec:
      serviceAccount: node-controller
      serviceAccountName: node-controller
      containers:
      - name: terminated-node-removal
        image: annavarsatish/node-removal:1.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      - name: alpine
        image: annavarsatish/node-removal:1.2
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
